### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by atagmester**
Added installation instructions for  FreeBSD

### CODE REVIEW

**Comment by user234683** [comment]
Is there a way to use the latest or system version of python? One day 3.9 will be unmaintained or conflict with other versions on the system, no?

**Comment by atagmester** [comment]
> Is there a way to use the latest or system version of python? One day 3.9 will be unmaintained or conflict with other versions on the system, no?

Of course...
Note: new (24.2.1) version of gevent is bugged, we have to use the previous version... + still need to install py-sqlite3 manually.
Steps (tested on FreeBSD 13.2-RELEASE-p4):

Install python 3.11 (with sqlite3)
`pkg install python311 py311-sqlite3`

Install pip
`python3.11 -m ensurepip --upgrade`

Optional: create a virtual environment:
`python3.11 -m venv env`
`source env/bin/activate.csh`

Install previous version of gevent
`pip3.11 install gevent==23.9.1`

Install everything else
`pip3.11 install -r requirements.txt`

Then start the server
`python3.11 server.py`

Optional: to exit the virtual env, just type
`deactivate`

**Comment by user234683** [comment]
I meant moreso not referring to any particular python version (e.g. `pkg install py-gevent py-sqlite3` rather than `pkg install py39-gevent py39-sqlite3`), otherwise the installation instructions will need to be updated continuously. If it's not possible or 3.9 is expected to be the applicable version for a long time, we can just go with your original PR.

**Comment by atagmester** [comment]
Sadly no. The module names contain the version string in pkg... There's no "uniform" version like 'python3-sqlite3'
> py39-gevent-22.10.2            Python co-routine networking library based on greenlet

> py27-sqlite3-2.7.18_7          Standard Python binding to the SQLite3 library (Python 2.7)
py310-sqlite3-3.10.13_7        Standard Python binding to the SQLite3 library (Python 3.10)
py311-sqlite3-3.11.8_7         Standard Python binding to the SQLite3 library (Python 3.11)
py38-sqlite3-3.8.18_7          Standard Python binding to the SQLite3 library (Python 3.8)
py39-sqlite3-3.9.18_7          Standard Python binding to the SQLite3 library (Python 3.9)

My recommendation is to use py39-*, which is the default version atm

**Pull request merged**
