### PR TITLE
fix KeyError for authorless playlists

### PR DESCRIPTION
**Pull request by zrose584**
Btw, video_count is sometimes None on /watch, but works normal on /playlist.

### CODE REVIEW

**Comment by user234683** [comment]
Do you have sample urls that reproduce the video_count issue?

Also, I was only able to reproduce the KeyError issue with Youtube mixes (whose /playlist page is broken atm). Are there other authorless playlists? URL?

**Comment by zrose584** [comment]
How can I send you private messages?

**Comment by user234683** [comment]
You could email me at user234683@tutanota.com

**Comment by user234683** [comment]
So I found out that Tutanota deletes your account if you don't login for 6 months, so try sending it to james [ a._-...t] jtaylor [d.-_.o-._.-t] xyz

**Pull request closed without merging**
