### PR TITLE
Design Changes Mainlly Dark mode

### PR DESCRIPTION
**Pull request by prinixos**
Default css was nothing.. there was no css whats so ever I have added some icons which are mainly svg and changed the entire css

### CODE REVIEW

**Comment by user234683** [comment]
Thoughts:
- Using the YouTube logo isn't a good idea
- The homepage icons are too difficult/slow to identify. Text is easier and more descriptive. I think big icons like this are a good idea for a mobile interface though, provided the text describing each thing is always displayed, so I'll keep this idea in mind for when mobile support is added.
- Changing the color scheme of the search bar and other forms to match with dark mode is a good idea.
- More skeptical of removing the borders from page numbers and the expandable elements on the watch page. It moves more towards flat UI design, which I don't want to do.
- The additional padding on the expandable elements is a maybe. For a mobile design, the additional padding added to these and other elements are probably a good idea, so I'll remember to incorporate this as well.
- Using the magnifying glass icon for the search button is probably good. Saves space as well.
- Don't like adding space between videos in search results and channel pages
- Uncertain on changing the links to white in the dark theme. I think the dark theme needs some work, but I would like to get input from a number of users who use dark theme before doing it.
- I don't think rounding the elements is necessary.

For changes specific to the dark theme, do it in a separate pull request than general design changes. In general, the smaller and more targgeted a pull request, the easier it is to discuss and accept. Lots of unrelated changes will be unlikely to be accepted. Also when it comes to any major design changes, I will want most users to be onboard beforehand, or otherwise make the change optional.

**Comment by arankaren** [comment]
@prinixos What do you think about of https://git.sr.ht/~heckyel/yt-local ?

**Comment by prinixos** [comment]
Your design is flawless and fast best suted for the page but you have also some fetures to make it look like that too yet i dont think any one uses does features anyway so I think its relly good

**Comment by prinixos** [comment]
I understand the problems you are telling it was not my final build I have a lot of work to do not only in dark theme but in CSS only I have just sent you this to know that my rough idea of the project and you like it or not. And I know that there are icons which can slow the system but if you see I tried to make most of them inline SVG if available and I will change the home icons soon enough.

**Pull request closed without merging**
