### PR TITLE
Fix csp

### PR DESCRIPTION
**Pull request by zrose584**

### CODE REVIEW

**Comment by user234683** [comment]
What's being fixed here?

**Comment by zrose584** [comment]
Haven't you seen the force-push? I think it should be clear now.

**Comment by user234683** [comment]
I looked at the files changed tab, and no it's not exactly clear what was wrong. For instance, I checked with a print statement and haven't seen '//' infront of any thumbnails. Description of the issue being fixed is important because I don't know what issues you're experiencing or what motivated a change without guesswork.

**Comment by zrose584** [comment]
It happens on profile pictures (eg on /search).
The browser interprets `//` as `http://`, so the csp blocked these.

**Pull request closed without merging**
