### PR TITLE
feat: autoplay for related videos

### PR DESCRIPTION
**Pull request by Umimaso**
Add autoplay support for related videos.
Move the playlist autoplay code into this shared script.
Add the SameSite=Strict attribute to the autoplay cookie due to Firefox soon rejecting cookies which use SameSite=None without the secure attribute.

Closes: #50

### CODE REVIEW

**Comment by user234683** [comment]
Some issues:
- Playlist autoplay no longer works right - if you start from the first video, it doesn't remain in the playlist
- Enabling autoplay in a playlist enables global video autoplay. The code should assume that someone who enables global video autoplay will want playlist autoplay, but someone who only enables autoplay for a specifc playlist does not necessarily want global video autoplay (e.g. myself).
- The autoplay still occurs even if related videos are disabled in the settings or if the related videos are default-hidden. In either of those cases, the autoplay shouldn't happen and the checkbox shouldn't be visible since the related videos aren't visible.

**Comment by Umimaso** [comment]
Thanks for spotting these

- I missed the accidental breaking of first playlist videos and will resolve this.
- I intentionally changed the autoplay to be global, but after hearing your thoughts on it I'll change the flag to support playlist specific toggling.
- Nice catch on this one I didn't think of this case. I'll move the releated videos autoplay to within the dropdown and add a check to the script.

**Comment by Umimaso** [comment]
> The autoplay still occurs even if related videos are disabled in the settings or if the related videos are default-hidden. In either of those cases, the autoplay shouldn't happen and the checkbox shouldn't be visible since the related videos aren't visible.

Having the related videos mode set to "shown by clicking button" I think should still allow for the autoplay feature to occur if it's been toggled on. Just that the checkbox for it will only be displayed when the related videos list is expanded.

E.g If a user has the related videos list collapsed by default, but then expands it and enables autoplay. I would expect autoplay to occur for this video, and any videos after without requiring to re-expand the list. Requiring the list to be always shown doesn't feel right from a usability point. What are your thoughts on this?

**Comment by user234683** [comment]
Tough question. The answer to the best behavior depends on the user's reason for enabling autoplay, and the reason for setting the related videos to default hidden. A user might set related videos to default hidden (1) so as to not become distracted from the current video, and/or (2) so as to spend less time on Youtube/not kill time. I would speculate that a user enables autoplay either because they (1) want to kill time or (2) because they believe Youtube's default first suggestions provide a series of videos they find valuable/informative (but I'm not an autoplay user so might be wrong). In the first case, the user might not care about what's coming up, while in the second, the user might want to glance first in case it's not interesting.

Two cases for hidden related videos + autoplay:
1. Default shown, with autoplay on, but then the user hides them. I would speculate that this is because the user wishes to concentrate on the video and not be distracted by the other related videos. Since the user had the opportunity to see what's next, it probably makes sense to let autoplay proceed.
2. Default hidden, with autoplay on. There are two ways to reach this state: (1) enable autoplay, then go to settings and change to default hidden (2) other way around. (of course it would be too complex for code to distinguish these) The first sounds more like someone who wants to spend less time on Youtube, because the valueable-stream-of-content person would surely want a glance at what's next (so perhaps no autoplay is best in this case). I'm less sure about case 2.

You might have more intuition about autoplay, so you could choose either way. If the autoplay is going to happen the checkbox should always be visible so there aren't any surprises. Otherwise, if you decide the autoplay can't happen for default-hidden, then it shouldn't be present.

**Comment by Umimaso** [comment]
I've decided to keep the autoplay toggle always displayed unless the related videos feature is disabled. When the related videos feature is enabled the toggle will sit above the releated videos heading. This allows full visibility of it's state without it being hidden under the related videos list, and allows the user to easily change it's state.

**Pull request merged**
