### PR TITLE
add an option for setting default volume

### PR DESCRIPTION
**Pull request by yumpyy**
added an option to set default volume in the settings page.
please let me know if i should change anything o7

image

### CODE REVIEW

**Comment by user234683** [comment]
We should also make it possible for it to not do anything and use that as the default (i.e. let the browser pick the volume, since in some setups, people might have extensions or other settings that already set the default volume). Easiest way may be to let the min value (and also the default) be -1 and then in that case don't set the volume field in the plyr-start.js (I think you can set it to `null` and that should do the trick)

**Comment by yumpyy** [comment]
here is a patch i wrote. im not sure how to test it though. when a default volume is not set, plyr defaults to 100%.
https://termbin.com/nrib

> I think you can set it to null and that should do the trick

plyr only allows value from 0 to 1 for `volume` option. setting it to null isnt possible, so i had to change existing code a little bit.

**Comment by user234683** [comment]
> here is a patch i wrote. im not sure how to test it though. when a default volume is not set, plyr defaults to 100%. https://termbin.com/nrib
> 
> > I think you can set it to null and that should do the trick
> 
> plyr only allows value from 0 to 1 for `volume` option. setting it to null isnt possible, so i had to change existing code a little bit.

Looks good, just change the default to -1 and push another commit to this pull request and we can merge

**Comment by yumpyy** [comment]
done o7

**Pull request merged**
