### PR TITLE
Update dark theme (Only white elements)

### PR DESCRIPTION
**Pull request by Mageas**
Only update the colors of actual white elements.
Change the import position of the theme to override the default theme.

### CODE REVIEW

**Comment by user234683** [comment]
It does work, but only on very recent browser versions (e.g. it works on Firefox 91 but not 78 ESR on debian or ungoogled chromium 80). Only the checkboxes are darkened on the older browsers. I believe this is because the file-selector-button is only supported by very recent browsers, so it's getting `Unknown pseudo-class or pseudo-element ‘file-selector-button’.  Ruleset ignored due to bad selector.` in the console and the entire rule is not applied.

Also, why did the playlist name input get a search-box class?

**Comment by Mageas** [comment]
The search-box class for the playlist name input was a mistake, I was testing things and forgot to remove it.

I have added `::-webkit-file-upload-button` for [backward compatibility](https://caniuse.com/?search=file-selector-button).

**Comment by user234683** [comment]
The ruleset for all the other buttons still doesn't get applied because the browser is throwing the entire thing out because of the unsupported `::file-upload-button`. (lines 49 and 64)

**Comment by Mageas** [comment]
Can I get your browser and your browser version (if you want to give me) so I can test without annoying you.

**Comment by user234683** [comment]
Reproducible on all of these:

- Firefox 78 ESR
- Ungoogled chromium 80
- Waterfox Classic 2021.08.1 (pre-quantum firefox fork)

Essentially, any browser version that doesn't support `::file-upload-button`. Additionally `::-webkit-file-upload-button` is supported by older chrome versions, but not older firefox versions.

**Comment by Mageas** [comment]
I have removed the customization for the `browse button`. There are two ways to style the button.
1: Custom a browse button and link it with some js.
2: Hide the real `browse button` behind a custom button.

I hate js, and I'm not a fan of the second way either, I think it is not a problem if this element remains white. We don't spend much time in the subscription_manager section.

**Comment by user234683** [comment]
Looks great, thanks!

**Pull request merged**
